/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ContributionTrackerInterface extends Interface {
    getFunction(nameOrSignature: "closeProject" | "contributionCount" | "contributionPoints" | "contributions" | "createProject" | "disputeCount" | "disputes" | "fileHashToContribId" | "getLeaderboard" | "memberScores" | "projectCount" | "projects" | "raiseDispute" | "submitContribution" | "verifyFile" | "voteOnDispute"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ContributionSubmitted" | "DisputeRaised" | "DisputeResolved" | "ProjectCreated" | "ScoreUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'closeProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'contributionCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'contributionPoints', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'contributions', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createProject', values: [string, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'disputeCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'disputes', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fileHashToContribId', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getLeaderboard', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'memberScores', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'projectCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'projects', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'raiseDispute', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'submitContribution', values: [BigNumberish, string, BigNumberish, string, BytesLike]): string;
encodeFunctionData(functionFragment: 'verifyFile', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'voteOnDispute', values: [BigNumberish, boolean]): string;

    decodeFunctionResult(functionFragment: 'closeProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contributionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contributionPoints', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputeCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fileHashToContribId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLeaderboard', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'memberScores', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projectCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projects', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'raiseDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitContribution', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyFile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voteOnDispute', data: BytesLike): Result;
  }

  
    export namespace ContributionSubmittedEvent {
      export type InputTuple = [contribId: BigNumberish, contributor: AddressLike, points: BigNumberish];
      export type OutputTuple = [contribId: bigint, contributor: string, points: bigint];
      export interface OutputObject {contribId: bigint, contributor: string, points: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeRaisedEvent {
      export type InputTuple = [disputeId: BigNumberish, contribId: BigNumberish, raisedBy: AddressLike];
      export type OutputTuple = [disputeId: bigint, contribId: bigint, raisedBy: string];
      export interface OutputObject {disputeId: bigint, contribId: bigint, raisedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeResolvedEvent {
      export type InputTuple = [disputeId: BigNumberish, contributionKept: boolean];
      export type OutputTuple = [disputeId: bigint, contributionKept: boolean];
      export interface OutputObject {disputeId: bigint, contributionKept: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectCreatedEvent {
      export type InputTuple = [projectId: BigNumberish, name: string, admin: AddressLike];
      export type OutputTuple = [projectId: bigint, name: string, admin: string];
      export interface OutputObject {projectId: bigint, name: string, admin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ScoreUpdatedEvent {
      export type InputTuple = [projectId: BigNumberish, member: AddressLike, newScore: BigNumberish];
      export type OutputTuple = [projectId: bigint, member: string, newScore: bigint];
      export interface OutputObject {projectId: bigint, member: string, newScore: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ContributionTracker extends BaseContract {
    
    connect(runner?: ContractRunner | null): ContributionTracker;
    waitForDeployment(): Promise<this>;

    interface: ContributionTrackerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    closeProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    contributionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    contributionPoints: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    contributions: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, string, string, bigint, bigint, boolean] & {id: bigint, projectId: bigint, contributor: string, taskTitle: string, contribType: bigint, ipfsCID: string, fileHash: string, timestamp: bigint, points: bigint, disputed: boolean }],
      'view'
    >
    

    
    createProject: TypedContractMethod<
      [name: string, members: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    disputeCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    disputes: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, boolean] & {contribId: bigint, raisedBy: string, reason: string, votesFor: bigint, votesAgainst: bigint, resolved: boolean }],
      'view'
    >
    

    
    fileHashToContribId: TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getLeaderboard: TypedContractMethod<
      [projectId: BigNumberish, ],
      [[string[], bigint[]]],
      'view'
    >
    

    
    memberScores: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    projectCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    projects: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, boolean] & {id: bigint, name: string, admin: string, isActive: boolean }],
      'view'
    >
    

    
    raiseDispute: TypedContractMethod<
      [contributionId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    submitContribution: TypedContractMethod<
      [projectId: BigNumberish, taskTitle: string, contribType: BigNumberish, ipfsCID: string, fileHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifyFile: TypedContractMethod<
      [fileHash: BytesLike, ],
      [[boolean, bigint]],
      'view'
    >
    

    
    voteOnDispute: TypedContractMethod<
      [disputeId: BigNumberish, keepContribution: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'closeProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'contributionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'contributionPoints'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'contributions'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, string, string, bigint, bigint, boolean] & {id: bigint, projectId: bigint, contributor: string, taskTitle: string, contribType: bigint, ipfsCID: string, fileHash: string, timestamp: bigint, points: bigint, disputed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'createProject'): TypedContractMethod<
      [name: string, members: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'disputeCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'disputes'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, boolean] & {contribId: bigint, raisedBy: string, reason: string, votesFor: bigint, votesAgainst: bigint, resolved: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'fileHashToContribId'): TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getLeaderboard'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [[string[], bigint[]]],
      'view'
    >;
getFunction(nameOrSignature: 'memberScores'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'projectCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'projects'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, boolean] & {id: bigint, name: string, admin: string, isActive: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'raiseDispute'): TypedContractMethod<
      [contributionId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitContribution'): TypedContractMethod<
      [projectId: BigNumberish, taskTitle: string, contribType: BigNumberish, ipfsCID: string, fileHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyFile'): TypedContractMethod<
      [fileHash: BytesLike, ],
      [[boolean, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'voteOnDispute'): TypedContractMethod<
      [disputeId: BigNumberish, keepContribution: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ContributionSubmitted'): TypedContractEvent<ContributionSubmittedEvent.InputTuple, ContributionSubmittedEvent.OutputTuple, ContributionSubmittedEvent.OutputObject>;
getEvent(key: 'DisputeRaised'): TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'ProjectCreated'): TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
getEvent(key: 'ScoreUpdated'): TypedContractEvent<ScoreUpdatedEvent.InputTuple, ScoreUpdatedEvent.OutputTuple, ScoreUpdatedEvent.OutputObject>;

    filters: {
      
      'ContributionSubmitted(uint256,address,uint256)': TypedContractEvent<ContributionSubmittedEvent.InputTuple, ContributionSubmittedEvent.OutputTuple, ContributionSubmittedEvent.OutputObject>;
      ContributionSubmitted: TypedContractEvent<ContributionSubmittedEvent.InputTuple, ContributionSubmittedEvent.OutputTuple, ContributionSubmittedEvent.OutputObject>;
    

      'DisputeRaised(uint256,uint256,address)': TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
      DisputeRaised: TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
    

      'DisputeResolved(uint256,bool)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'ProjectCreated(uint256,string,address)': TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
      ProjectCreated: TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
    

      'ScoreUpdated(uint256,address,uint256)': TypedContractEvent<ScoreUpdatedEvent.InputTuple, ScoreUpdatedEvent.OutputTuple, ScoreUpdatedEvent.OutputObject>;
      ScoreUpdated: TypedContractEvent<ScoreUpdatedEvent.InputTuple, ScoreUpdatedEvent.OutputTuple, ScoreUpdatedEvent.OutputObject>;
    
    };
  }